#ifndef ENVIRONMENTOPTIONS_H_INCLUDED
#define ENVIRONMENTOPTIONS_H_INCLUDED

#define _MAX_CONNECTIONS 30
#define _MAX_CONNECTIONS 30
#define _ACCEPT_TIMEOUT 100
#define _SERVER_PORT 7777

#endif // ENVIRONMENTOPTIONS_H_INCLUDED
